version: 2

jobs:
  bozoi:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u donatello -p $DOCKER_PASS
          docker build -t donatello/bozoi:build-9 .
          docker push donatello/bozoi:build-9
          docker build -t donatello/bozoi:sqitch-1 -f Dockerfile.sqitch .
          docker push donatello/bozoi:sqitch-1

workflows:
  version: 2
  build:
    jobs:
      - bozoi
