version: 2

jobs:
  bozoi-ghc:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u donatello -p $DOCKER_PASS
          docker build -t donatello/bozoi:lts-12.0 .
          docker push donatello/bozoi:lts-12.0

workflows:
  version: 2
  build:
    jobs:
      - bozoi-ghc
